# Generated by Django 2.2.5 on 2019-10-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIcon',
        ),
    ]
