# Generated by Django 2.2.5 on 2019-10-16 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191016_0526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserIcon',
        ),
    ]
