# Generated by Django 2.2.5 on 2019-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
