# Generated by Django 2.2.5 on 2019-10-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_ticket_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='discount',
        ),
    ]
