# Generated by Django 2.2.5 on 2019-10-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_remove_ticket_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=10),
        ),
    ]
