# Generated by Django 2.2.5 on 2019-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AddField(
            model_name='order',
            name='off',
            field=models.DecimalField(decimal_places=2, default=0.15, max_digits=10),
        ),
    ]
