# Generated by Django 2.2.5 on 2019-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
